function main() {
    try {
        console.log("Hello");
    } catch (err) {
        console.log(err);
    }
};

main();